spring:

  data:
    mongodb:
      uri: mongodb+srv://match:5ZWAMf4byyKoPHso@clusterpropostaaceita-yhkgq.mongodb.net/test?retryWrites=true&w=majority
      database: match

services:

  internal:
    username: internal
    password: yblYhVyCtFB0aSm5

  notification:
    name: notification-service
    url: https://notification-pa-service.herokuapp.com
    username: internal
    password: wUrw93cGGYczZKsU